version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ideafactory_postgres
    environment:
      POSTGRES_DB: ideafactory_db
      POSTGRES_USER: ideafactory_user
      POSTGRES_PASSWORD: ideafactory_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - idea-network
    restart: unless-stopped

  # Spring Boot Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ideafactory_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ideafactory_db
      - SPRING_DATASOURCE_USERNAME=ideafactory_user
      - SPRING_DATASOURCE_PASSWORD=ideafactory_pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
    volumes:
      - ./backend:/app
      - /app/target
    depends_on:
      - postgres
    networks:
      - idea-network
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ideafactory_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - REACT_APP_ADMIN_URL=http://localhost:3000/admin
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - idea-network
    restart: unless-stopped

  # pgAdmin (Optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ideafactory_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ideafactory.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - idea-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  idea-network:
    driver: bridge 